version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./code:/code
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php_project
  php_project:
    build: .
    volumes:
      - ./code:/code
      - ./php/xdebug.conf:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_IDE_CONFIG: 'serverName=hdm'